#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Apr 13 16:47:15 MSK 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.7.1.zip
enableShaders=true
